CI: Switch to libgl1-mesa-dev and xorg-dev; add .gopherci.yml.
Travis fails (only now, for some reason) to build with libgles2-mesa-dev
APT package only:

	# github.com/go-gl/glfw/v3.2/glfw
	In file included from ./glfw/src/internal.h:169:0,
	                 from ./glfw/src/context.c:28,
	                 from ../../go-gl/glfw/v3.2/glfw/c_glfw.go:4:
	./glfw/src/x11_platform.h:39:33: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
	 #include <X11/Xcursor/Xcursor.h>
	                                 ^
	compilation terminated.

APT packages libgl1-mesa-dev and xorg-dev should be used because
github.com/goxjs/gl uses OpenGL 2.1 backend on Linux via
github.com/go-gl/gl/2.1/gl now.

Add .gopherci.yml for GopherCI.